stages:
  - test
  - deploy

test:
  stage: test
  image: golang:1.14.9-buster
  script:
    - go test ./

deploy:
  stage: deploy
  before_script:
    - mkdir -p .ssh
    - chmod 700 .ssh
    - echo "$SSH_PRIVATE_KEY" >> .ssh/rsa
    - chmod 700 .ssh/rsa
  script:
    - | 
      ssh -o StrictHostKeyChecking=no $user@$host -tt "
      cd million-singer
      docker-compose build
      docker-compose restart web
      "
