stages:
  - build
  - test
  - deploy


build:
  stage: build
  services:
    - docker:dind
  image: docker:latest
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

# test:
#   stage: test
#   image: golang:1.14.9-buster
#   script:
#     - go test ./

deploy:
  stage: deploy
  before_script:
    - mkdir -p .ssh
    - chmod 700 .ssh
    - echo "$SSH_PRIVATE_KEY" >> .ssh/rsa
    - chmod 700 .ssh/rsa
  script:
    - | 
      ssh -o StrictHostKeyChecking=no -i .ssh/rsa $HOST -tt "
      cd million-singer
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      docker-compose up -d
      "
