version: '3'
services:
  web:
    environment:
      db_user: ${db_user}
      db_passwd: ${db_passwd}
      db_host: ${db_host}
      db_name: ${db_name}
      db_table_prefix: ${db_table_prefix}
      server_runmode: ${server_runmode}
      server_port: ${server_port}
    build: .
    ports:
      - 80:8000
    links:
      - db
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    restart: always
    command: --init-file /init.sql 
             --default-authentication-plugin=mysql_native_password
             --character-set-server=utf8mb4
             --collation-server=utf8mb4_general_ci
             --explicit_defaults_for_timestamp=true
             --lower_case_table_names=1
             --max_allowed_packet=128M;
    environment:
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_passwd}
      MYSQL_ROOT_PASSWORD: ${db_passwd}
      MYSQL_DATABASE: ${db_name}
    volumes:
      - ./sql/init.sql:/init.sql
      - data:/var/lib/mysql

volumes:
  data: {}