# An example of conf.toml
[database]
Type = "mysql"
User = "database_user"
Password = "database_passwd"
Host = "mysql"
Name = "million_singer"
TablePrefix = "ms_"

[server]
RunMode = "debug"
HttpPort = 8000
