apiVersion: apps/v1
kind: Deployment
metadata:
  name: million-singer
spec:
  selector:
    matchLabels:
      app: million-singer
  template:
    metadata:
      labels:
        app: million-singer
    spec:
      containers:
      - name: million-singer
        image: jameshwc/million-singer:no-wait-it.sh
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
          - name: db_type
            value: mysql
          - name: db_user
            value: root
          - name: db_passwd
            value: database
          - name: db_host
            value: db
          - name: db_name
            value: million_singer
          - name: server_runmode
            value: debug
          - name: server_port
            value: "8000"
          - name: server_jwt_secret
            value: secret
          - name: redis_host
            value: redis
          - name: redis_port
            value: "6379"
          - name: redis_min_idle_conn
            value: "30"
          - name: redis_idle_timeout
            value: "200"
          - name: logstash_addr
            value: logstash:5000
          - name: log_is_enabled
            value: "0"
