apiVersion: v1
kind: PersistentVolume
metadata:
  name: million-singer-pv
spec:
  storageClassName: million-singer-storage-class
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: million-singer-storage
  gcePersistentDisk:
    pdName: million-singer-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: million-singer-storage
spec:
  storageClassName: million-singer-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: million-singer-storage-class
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none