apiVersion: v1
kind: Service
metadata:
  name: million-singer-redis
  labels:
    app: million-singer
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: million-singer
    type: cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: million-singer-redis
  labels:
    app: million-singer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: million-singer
      type: cache
  template:
    metadata:
      labels:
        app: million-singer
        type: cache
    spec:
      containers:
      - name: redis
        image: redis:6.0.8-alpine
        ports:
          - containerPort: 6379
            name: "redis"